### PR TITLE
fix: missing metrics

### LINKED ISSUE #11988: Missing metrics in AI plugin
### Describe the issue

- [ ] plugin-ai/src/main/java/io/kestra/plugin/ai/AIUtils.java

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Raj-G07**
- Closes https://github.com/kestra-io/kestra/issues/11988

### CODE REVIEW

File: src/main/java/io/kestra/plugin/ai/AIUtils.java [hunk 1]
```diff
@@ -17,6 +19,29 @@
 
 import static io.kestra.core.utils.Rethrow.throwConsumer;
 
+@Plugin(
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/ai/AIUtils.java]: @Raj-G07 ⚠️ No, you don't have to add a `@Plugin` annotation here since it's just a util class.

Instead you have to search for all calls to `sendMetrics` method:

Image

For those which are actual plugins with an existing `@Plugin` annotation, then you'll have to add the `@Metric` annotations with appropriate names.

Comment (Raj-G07) [reply src/main/java/io/kestra/plugin/ai/AIUtils.java]: My bad 😐

**Review by fdelbrayelle — APPROVED** [review]
