### PR TITLE
fix: support for bulkSize while ingesting

### LINKED ISSUE #249: IngestDocument is sending all the document in 1 request
### Describe the issue

If I have a lot of document in my rag, using `IngestDocument` will send all the document inside a single request.

We need to add a `bulkSize` (name TDB) parameters (default 500) that will segment the list of docs. 

Example error with elastic embedding store: 

```
2026-01-28 23:20:32.883dev.langchain4j.store.embedding.elasticsearch.ElasticsearchRequestFailedException: method [POST], host [https://elasticsearch.xxx.kestra.io],/ URI [/_bulk], status line [HTTP/1.1 413 Request Entity Too Large]
at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.addAll(ElasticsearchEmbeddingStore.java:348)
	at dev.langchain4j.store.embedding.EmbeddingStore.addAll(EmbeddingStore.java:66)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:202)
	at io.kestra.plugin.ai.rag.IngestDocument.run(IngestDocument.java:185)
	at io.kestra.plugin.ai.rag.IngestDocument.run(IngestDocument.java:37)
	at io.kestra.worker.WorkerTaskCallable.doCall(WorkerTaskCallable.java:81)
	at io.kestra.worker.AbstractWorkerCallable.call(AbstractWorkerCallable.java:64)
	at io.kestra.ee.worker.WorkerSecurityService.lambda$callInSecurityContext$0(WorkerSecurityService.java:30)
	at io.kestra.ee.sandbox.SecurityContextHolder.callInSecurityContext(SecurityContextHolder.java:22)
	at io.kestra.ee.worker.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:28)
	at io.kestra.worker.DefaultWorker.lambda$callJob$18(DefaultWorker.java:981)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.worker.DefaultWorker.callJob(DefaultWorker.java:977)
	at io.kestra.worker.DefaultWorker.runAttempt(DefaultWorker.java:926)
	at io.kestra.worker.DefaultWorker.run(DefaultWorker.java:720)
	at io.kestra.worker.DefaultWorker.handleTask(DefaultWorker.java:411)
	at io.kestra.worker.DefaultWorker.lambda$run$8(DefaultWorker.java:289)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://elasticsearch.xxx.kestra.io],/ URI [/_bulk], status line [HTTP/1.1 413 Request Entity Too Large]
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest(RestClientHttpClient.java:92)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:138)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.bulk(ElasticsearchClient.java:531)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.bulkIndex(ElasticsearchEmbeddingStore.java:369)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.addAll(ElasticsearchEmbeddingStore.java:346)
	... 20 more
```

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Malaydewangan09**
closes #249 

### What changes are being made and why?

---

### How the changes have been QAed?

---

### Setup Instructions

---

### Contributor Checklist ✅

- [ ] I have read and followed the [plugin contribution guidelines](https://kestra.io/docs/plugin-developer-guide/contribution-guidelines)

### CODE REVIEW

File: src/main/java/io/kestra/plugin/ai/rag/IngestDocument.java [hunk 1]
```diff
@@ -141,6 +141,13 @@ public class IngestDocument extends Task implements RunnableTask<IngestDocument.
     @Builder.Default
     private Property<Boolean> drop = Property.ofValue(Boolean.FALSE);
 
+    @Schema(
+        title = "Bulk ingestion size",
+        description = "Maximum number of documents sent per ingestion request."
+    )
+    @Builder.Default
+    private Property<@Min(1) Integer> bulkSize = Property.ofValue(500);
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/ai/rag/IngestDocument.java:149]: The `Min(1)` will introduce a breaking change forcing users to use this property right?

Comment (Malaydewangan09) [reply src/main/java/io/kestra/plugin/ai/rag/IngestDocument.java:149]: Hmm, we have a default value already no?

Comment (fdelbrayelle) [reply src/main/java/io/kestra/plugin/ai/rag/IngestDocument.java:149]: Ah yes it should be good enough then

**Review by fdelbrayelle — APPROVED** [review]
